import Dashboard from '@/components/Dashboard'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className='bg-slate-500'>
                    <Dashboard />
                </div>
                <div>
                    <Header />
                </div>
                {children}
            </body>
        </html>
    )
}
